apiVersion: v1
kind: Service
metadata:
  name: hero-manager-statistics
  labels:
    name: hero-manager-statistics
spec:
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    name: hero-manager-statistics
