apiVersion: apps/v1
kind: Deployment
metadata:
  name: hero-manager-statistics
  labels:
    name: hero-manager-statistics
spec:
  selector:
    matchLabels:
      name: hero-manager-statistics
  replicas: 1
  template:
    metadata:
      labels:
        name: hero-manager-statistics
    spec:
      containers:
        - name: hero-manager-statistics
          image: docker.io/library/hero_manager_statistics_image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          resources: {}
          env:
            - name: DB_HOST
              value: hero-manager-database
            - name: DB_PORT
              value: "27017"
            - name: DB_NAME
              value: heroManager
            - name: PORT
              value: "8083"
