apiVersion: v1
kind: Service
metadata:
  name: hero-manager-frontend
  labels:
    name: hero-manager-frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: hero-manager-frontend
