apiVersion: v1
kind: Service
metadata:
  name: hero-manager-scheduler
  labels:
    name: hero-manager-scheduler
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    name: hero-manager-scheduler
