apiVersion: v1
kind: Service
metadata:
  name: hero-manager-backend
  labels:
    name: hero-manager-backend
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    name: hero-manager-backend
