bases:
  - ../kubernetes
  - ingress/ingress.yaml
patches:
  - services/backend/backend.deployment.yaml
  - services/frontend/frontend.deployment.yaml
  - services/marvel/marvel.deployment.yaml
  - services/scheduler/scheduler.deployment.yaml
  - services/statistics/statistics.deployment.yaml
